FROM richarvey/nginx-php-fpm

MAINTAINER LordGift


# place config out of web directory.
#COPY config.ini /var/www/config.ini

#RUN mkdir -p /home/thaiinfi/etc/thaiinfinityrestaurant.com/backoffice/upload/
#RUN chown nginx:nginx /home/thaiinfi/etc/thaiinfinityrestaurant.com/backoffice/upload/
#
#RUN echo  "upload_tmp_dir=/home/thaiinfi/etc/thaiinfinityrestaurant.com/backoffice/upload/" > /usr/local/etc/php/conf.d/docker-vars-custom.ini
